explicitly require('fs') in tap reporter
Fixes a bug caused when run in a project that does not already include fs, the following error message is produced:

    ReferenceError: fs is not defined
        at Object.exports.run (/.../node_modules/nodeunit/lib/reporters/tap.js:27:23)
        at task.async [as action] (/.../Jakefile.js:20:12)